### ISSUE TITLE
Вектор развития

### ISSUE THREAD

**Issue by decatile** [swag-org/swag#1]
По описанию непонятно, куда двигается библиотека. Было бы круто добавить некоторую роадмапу, по которой коммьюнити могло бы ориентироваться и пилить фичи вместе с автором

**Comment by BoolmanO** [comment]
Now I'm working on the documentation, as soon as I finish the most basic things I will put it in the public domain. Maybe some kind of roadmap is really a good idea

**Comment by BoolmanO** [comment]
https://github.com/swag-org/swag#swag-roadmap
Это оно? Если есть какие-то уточнения или пожелания можете сказать. В будущем, очевидно, будут реализованы концепты мидлваров и, возможно, созданы различные библиотеки, которые как гирлянды будут вешаться на swag и делать из него "фреймворк", но сейчас самое важное сделать основу - тесты (CI&CD), доки. Возможно рефакторинг кода.

**Comment by decatile** [comment]
Угу, оно. Больше вопросов нет
